interface Timed {
    timestamp: number;
}
export interface Token {
    access_token: string;
    token_type: string;
    expires_in: number;
    refresh_token: string;
    created_at: number;
}

export interface Vehicle {
    id: number;
    vehicle_id: number;
    vin: string;
    display_name: string;
    option_codes: string;
    access_type: string;
    tokens: string[];
    state: 'online' | 'offline' | 'asleep';
    in_service: boolean;
    id_s: string;
    calendar_enabled: boolean;
    api_version: number;
    backseat_token: null;
    backseat_token_updated_at: null;
    vehicle_config: any | null;
}

export interface Climate extends Timed {
    battery_heater: boolean;
    battery_heater_no_power: any;
    climate_keeper_mode: string;
    defrost_mode: number;
    driver_temp_setting: number;
    fan_status: number;
    inside_temp: number;
    is_auto_conditioning_on: boolean;
    is_climate_on: boolean;
    is_front_defroster_on: boolean;
    is_preconditioning: boolean;
    is_rear_defroster_on: boolean;
    left_temp_direction: number;
    max_avail_temp: number;
    min_avail_temp: number;
    outside_temp: number;
    passenger_temp_setting: number;
    remote_heater_control_enabled: boolean;
    right_temp_direction: number;
    seat_heater_left: number;
    seat_heater_right: number;
    side_mirror_heaters: boolean;
    wiper_blade_heater: boolean;
}
export interface VehicleData {
    id: number;
    user_id: number;
    vehicle_id: number;
    vin: string;
    display_name: string;
    option_codes: string;
    color: null;
    access_type: 'OWNER' | string;
    tokens: string[];
    state: 'online' | 'asleep' | 'offline';
    in_service: boolean;
    id_s: string;
    calendar_enabled: boolean;
    api_version: 10;
    backseat_token: null;
    backseat_token_updated_at: null;
    vehicle_config: Timed & {
        can_accept_navigation_requests: boolean;
        can_actuate_trunks: boolean;
        car_special_type: 'base' | string;
        car_type: 'model3' | string;
        charge_port_type: 'CCS' | string;
        ece_restrictions: boolean;
        eu_vehicle: boolean;
        exterior_color: string;
        has_air_suspension: boolean;
        has_ludicrous_mode: boolean;
        key_version: 2;
        motorized_charge_port: boolean;
        plg: boolean;
        rear_seat_heaters: 0;
        rear_seat_type: null;
        rhd: boolean;
        roof_color: string;
        seat_type: null;
        spoiler_type: string;
        sun_roof_installed: null;
        third_row_seats: '<invalid>';
        trim_badging: string;
        use_range_badging: boolean;
        wheel_type: string;
    };
    charge_state: Timed & {
        battery_heater_on: boolean;
        battery_level: number;
        battery_range: number;
        charge_current_request: number;
        charge_current_request_max: number;
        charge_enable_request: boolean;
        charge_energy_added: number;
        charge_limit_soc: number;
        charge_limit_soc_max: number;
        charge_limit_soc_min: number;
        charge_limit_soc_std: number;
        charge_miles_added_ideal: number;
        charge_miles_added_rated: number;
        charge_port_cold_weather_mode: boolean;
        charge_port_door_open: boolean;
        charge_port_latch: 'Engaged' | string;
        charge_rate: number;
        charge_to_max_range: boolean;
        charger_actual_current: number;
        charger_phases: null;
        charger_pilot_current: number;
        charger_power: number;
        charger_voltage: number;
        charging_state: 'Disconnected' | string;
        conn_charge_cable: '<invalid>';
        est_battery_range: number;
        fast_charger_brand: '<invalid>';
        fast_charger_present: boolean;
        fast_charger_type: '<invalid>';
        ideal_battery_range: number;
        managed_charging_active: boolean;
        managed_charging_start_time: null;
        managed_charging_user_canceled: boolean;
        max_range_charge_counter: number;
        minutes_to_full_charge: number;
        not_enough_power_to_heat: null;
        scheduled_charging_pending: boolean;
        scheduled_charging_start_time: null;
        time_to_full_charge: number;
        trip_charging: boolean;
        usable_battery_level: number;
        user_charge_enable_request: null;
    };
    climate_state: Timed & {
        battery_heater: boolean;
        battery_heater_no_power: null;
        climate_keeper_mode: 'off';
        defrost_mode: 0;
        driver_temp_setting: number;
        fan_status: number;
        inside_temp: number;
        is_auto_conditioning_on: boolean;
        is_climate_on: boolean;
        is_front_defroster_on: boolean;
        is_preconditioning: boolean;
        is_rear_defroster_on: boolean;
        left_temp_direction: number;
        max_avail_temp: number;
        min_avail_temp: number;
        outside_temp: number;
        passenger_temp_setting: number;
        remote_heater_control_enabled: boolean;
        right_temp_direction: number;
        seat_heater_left: number;
        seat_heater_right: number;
        side_mirror_heaters: boolean;
        wiper_blade_heater: boolean;
    };
    drive_state: Timed & {
        gps_as_of: number;
        heading: number;
        latitude: number;
        longitude: number;
        native_latitude: number;
        native_location_supported: number;
        native_longitude: number;
        native_type: 'wgs';
        power: number;
        shift_state: null;
        speed: null;
    };
    gui_settings: Timed & {
        gui_24_hour_time: boolean;
        gui_charge_rate_units: 'km/hr' | string;
        gui_distance_units: 'km/hr' | string;
        gui_range_display: 'Rated' | string;
        gui_temperature_units: 'C' | 'F';
        show_range_units: boolean;
    };
    vehicle_state: Timed & {
        api_version: number;
        autopark_state_v2: 'unavailable';
        calendar_supported: boolean;
        car_version: string;
        center_display_state: 0;
        df: number;
        dr: number;
        fd_window: number;
        fp_window: number;
        ft: number;
        is_user_present: boolean;
        locked: boolean;
        media_state: {
            remote_control_enabled: boolean;
        };
        notifications_supported: boolean;
        odometer: number;
        parsed_calendar_supported: boolean;
        pf: number;
        pr: number;
        rd_window: number;
        remote_start: boolean;
        remote_start_enabled: boolean;
        remote_start_supported: boolean;
        rp_window: number;
        rt: number;
        sentry_mode: boolean;
        sentry_mode_available: boolean;
        software_update: {
            download_perc: number;
            expected_duration_sec: number;
            install_perc: number;
            status: string;
            version: string;
        };
        speed_limit_mode: {
            active: boolean;
            current_limit_mph: number;
            max_limit_mph: number;
            min_limit_mph: number;
            pin_code_set: boolean;
        };
        valet_mode: boolean;
        valet_pin_needed: boolean;
        vehicle_name: string;
    };
}
